package com.siveet.negocio.servicios.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 20 15:31:08 COT 2015
// ---------------------------------------------------------------------
public interface SeguridadServicio extends ApplicationModule {
  Row buscarUsuario(String alias, String clave);
}

