CREATE TABLE ATENCION 
(
  CODIGO_ATENCION INTEGER NOT NULL 
, CODIGO_CLIENTE INTEGER NOT NULL 
, CODIGO_EMPLEADO INTEGER NOT NULL 
, MONTO NUMBER(*, 2) NOT NULL 
, ESTADO CHAR DEFAULT '1' NOT NULL 
, FECHA_REGISTRO DATE DEFAULT SYSDATE NOT NULL 
, CONSTRAINT ATENCION_PK PRIMARY KEY 
  (
    CODIGO_ATENCION 
  )
  ENABLE 
);

CREATE TABLE ATENCION_DETALLE 
(
  CODIGO_DETALLE INTEGER NOT NULL 
, CODIGO_ATENCION INTEGER NOT NULL 
, CODIGO_MASCOTA INTEGER NOT NULL 
, CODIGO_EMPLEADO INTEGER 
, CODIGO_SERVICIO INTEGER NOT NULL 
, FECHA_ATENCION DATE 
, FECHA_REGISTRO DATE DEFAULT SYSDATE NOT NULL 
, OBSERVACIONES VARCHAR2(200) 
, CONSTRAINT ATENCION_DETALLE_PK PRIMARY KEY 
  (
    CODIGO_DETALLE 
  )
  ENABLE 
);

CREATE TABLE CLIENTE 
(
  CODIGO_CLIENTE INTEGER NOT NULL 
, DESCRIPCION VARCHAR2(150) NOT NULL 
, TIPO_DOCUMENTO CHAR(1) DEFAULT '1' NOT NULL 
, DOCUMENTO VARCHAR2(20) NOT NULL 
, DIRECCION VARCHAR2(200) 
, FECHA_NACIMIENTO DATE 
, RUC VARCHAR2(11) 
, TELEFONO VARCHAR2(10) 
, CORREO VARCHAR2(30) 
, SEXO CHAR(1) DEFAULT 'M' NOT NULL 
, ESTADO CHAR(1) DEFAULT '1' NOT NULL 
, USUARIO_REGISTRA INTEGER NOT NULL 
, FECHA_REGISTRO DATE DEFAULT SYSDATE NOT NULL 
, CONSTRAINT CLIENTE_PK PRIMARY KEY 
  (
    CODIGO_CLIENTE 
  )
  ENABLE 
);

CREATE TABLE COMPROBANTE_PAGO 
(
  CODIGO_COMPROBANTE INTEGER NOT NULL 
, CODIGO_ATENCION INTEGER NOT NULL 
, MONTO_ACUENTA NUMBER(*, 2) 
, MONTO_TOTAL NUMBER(*, 2) 
, CODIGO_EMPLEADO INTEGER 
, ESTADO CHAR(1) DEFAULT '1' 
, CONSTRAINT COMPROBANTE_PAGO_PK PRIMARY KEY 
  (
    CODIGO_COMPROBANTE 
  )
  ENABLE 
);

CREATE TABLE EMPLEADO 
(
  CODIGO_EMPLEADO INTEGER NOT NULL 
, DESCRIPCION VARCHAR2(150) NOT NULL 
, CARGO INTEGER NOT NULL 
, ESTADO CHAR(1) DEFAULT '1' NOT NULL 
, ALIAS VARCHAR2(20) NOT NULL 
, CLAVE VARCHAR2(10) NOT NULL 
, EMPLEADO_REGISTRA INTEGER NOT NULL 
, FECHA_REGISTRO DATE DEFAULT SYSDATE NOT NULL 
, CONSTRAINT EMPLEADO_PK PRIMARY KEY 
  (
    CODIGO_EMPLEADO 
  )
  ENABLE 
);

CREATE TABLE MASCOTA 
(
  CODIGO_ANIMAL INTEGER NOT NULL 
, CODIGO_CLIENTE INTEGER NOT NULL 
, RAZA INTEGER NOT NULL 
, NOMBRE VARCHAR2(30) NOT NULL 
, SEXO CHAR(1) DEFAULT 'M' NOT NULL 
, COLOR VARCHAR2(30) 
, CASTRADO CHAR(1) DEFAULT 0 NOT NULL 
, TAMANIO CHAR(1) DEFAULT 'M' NOT NULL 
, FECHA_NACIMIENTO DATE 
, DETALLES VARCHAR2(200) 
, CONSTRAINT ANIMAL_PK PRIMARY KEY 
  (
    CODIGO_ANIMAL 
  )
  ENABLE 
);

CREATE TABLE PRODUCTO 
(
  CODIGO_PRODUCTO INTEGER NOT NULL 
, TIPO_PRODUCTO INTEGER NOT NULL 
, NOMBRE VARCHAR2(150) NOT NULL 
, DESCRIPCION VARCHAR2(150) 
, MARCA VARCHAR2(50) NOT NULL 
, PRECIO VARCHAR2(30) NOT NULL 
, STOCK INTEGER NOT NULL 
, UNIDAD_MEDIDA INTEGER NOT NULL 
, ESTADO CHAR DEFAULT '1' NOT NULL 
, CONSTRAINT PRODUCTO_PK PRIMARY KEY 
  (
    CODIGO_PRODUCTO 
  )
  ENABLE 
);

CREATE TABLE RAZA 
(
  CODIGO_RAZA INTEGER NOT NULL 
, DESCRIPCION VARCHAR2(30) NOT NULL 
, TIPO_ANIMAL INTEGER NOT NULL 
, CONSTRAINT RAZA_PK PRIMARY KEY 
  (
    CODIGO_RAZA 
  )
  ENABLE 
);

CREATE TABLE SERVICIO 
(
  CODIGO_SERVICIO INTEGER NOT NULL 
, DESCRIPCION VARCHAR2(150) NOT NULL 
, PRECIO NUMBER(*, 2) NOT NULL 
, ESTADO CHAR(1) DEFAULT '1' NOT NULL 
, CONSTRAINT SERVICIO_PK PRIMARY KEY 
  (
    CODIGO_SERVICIO 
  )
  ENABLE 
);

CREATE TABLE TIPO_ANIMAL 
(
  CODIGO_TIPO INTEGER NOT NULL 
, DESCRIPCION VARCHAR2(30) NOT NULL 
, CONSTRAINT TIPO_ANIMAL_PK PRIMARY KEY 
  (
    CODIGO_TIPO 
  )
  ENABLE 
);

CREATE TABLE TIPO_PRODUCTO 
(
  CODIGO_TIPO INTEGER NOT NULL 
, DESCRIPCION VARCHAR2(20) NOT NULL 
, ESTADO CHAR(1) DEFAULT '1' NOT NULL 
, CONSTRAINT TIPO_PRODUCTO_PK PRIMARY KEY 
  (
    CODIGO_TIPO 
  )
  ENABLE 
);

CREATE TABLE TIPO_UNIDAD 
(
  CODIGO_TIPO INTEGER NOT NULL 
, DESCRIPCION VARCHAR2(50) NOT NULL 
, ESTADO CHAR(1) DEFAULT '1' NOT NULL 
, CONSTRAINT TIPO_UNIDAD_PK PRIMARY KEY 
  (
    CODIGO_TIPO 
  )
  ENABLE 
);

ALTER TABLE ATENCION
ADD CONSTRAINT ATENCION_FK1 FOREIGN KEY
(
  CODIGO_EMPLEADO 
)
REFERENCES EMPLEADO
(
  CODIGO_EMPLEADO 
)
ENABLE;

ALTER TABLE ATENCION
ADD CONSTRAINT ATENCION_FK2 FOREIGN KEY
(
  CODIGO_CLIENTE 
)
REFERENCES CLIENTE
(
  CODIGO_CLIENTE 
)
ENABLE;

ALTER TABLE ATENCION_DETALLE
ADD CONSTRAINT ATENCION_DETALLE_FK1 FOREIGN KEY
(
  CODIGO_MASCOTA 
)
REFERENCES MASCOTA
(
  CODIGO_ANIMAL 
)
ENABLE;

ALTER TABLE ATENCION_DETALLE
ADD CONSTRAINT ATENCION_DETALLE_FK2 FOREIGN KEY
(
  CODIGO_ATENCION 
)
REFERENCES ATENCION
(
  CODIGO_ATENCION 
)
ENABLE;

ALTER TABLE ATENCION_DETALLE
ADD CONSTRAINT ATENCION_DETALLE_FK3 FOREIGN KEY
(
  CODIGO_SERVICIO 
)
REFERENCES SERVICIO
(
  CODIGO_SERVICIO 
)
ENABLE;

ALTER TABLE COMPROBANTE_PAGO
ADD CONSTRAINT COMPROBANTE_PAGO_FK1 FOREIGN KEY
(
  CODIGO_ATENCION 
)
REFERENCES ATENCION
(
  CODIGO_ATENCION 
)
ENABLE;

ALTER TABLE MASCOTA
ADD CONSTRAINT ANIMAL_FK2 FOREIGN KEY
(
  CODIGO_CLIENTE 
)
REFERENCES CLIENTE
(
  CODIGO_CLIENTE 
)
ENABLE;

ALTER TABLE MASCOTA
ADD CONSTRAINT ANIMAL_RAZA_FK1 FOREIGN KEY
(
  RAZA 
)
REFERENCES RAZA
(
  CODIGO_RAZA 
)
ENABLE;

ALTER TABLE PRODUCTO
ADD CONSTRAINT PRODUCTO_FK1 FOREIGN KEY
(
  TIPO_PRODUCTO 
)
REFERENCES TIPO_PRODUCTO
(
  CODIGO_TIPO 
)
ENABLE;

ALTER TABLE PRODUCTO
ADD CONSTRAINT PRODUCTO_FK2 FOREIGN KEY
(
  UNIDAD_MEDIDA 
)
REFERENCES TIPO_UNIDAD
(
  CODIGO_TIPO 
)
ENABLE;

ALTER TABLE RAZA
ADD CONSTRAINT RAZA_FK1 FOREIGN KEY
(
  TIPO_ANIMAL 
)
REFERENCES TIPO_ANIMAL
(
  CODIGO_TIPO 
)
ENABLE;

COMMENT ON COLUMN ATENCION.CODIGO_EMPLEADO IS 'Código de empleado que genera la atención';

COMMENT ON COLUMN ATENCION.MONTO IS 'Monto total de todos los servicios';

COMMENT ON COLUMN ATENCION.ESTADO IS '1 Generado, 2 Atendido, 3 Anulado';

COMMENT ON COLUMN CLIENTE.TIPO_DOCUMENTO IS '1 DNI, 2 CE, 3 PASAPORTE , 4 DIE';

COMMENT ON COLUMN COMPROBANTE_PAGO.ESTADO IS '1:Pagado 2:ACuenta 3:Anulado';

COMMENT ON COLUMN MASCOTA.CASTRADO IS '0 No, 1 Si';

COMMENT ON COLUMN MASCOTA.TAMANIO IS 'P Pequeño, M Mediano, G Grande';

COMMENT ON COLUMN PRODUCTO.ESTADO IS '1 Disponible 2 No Disponible, 3 Vencido';
